db:
  name: ${DB_DATABASE}
  schema: ${DB_SCHEMA}
  ssl: ${DB_SSL:disable}
  port: ${DB_PORT:5432}
  host: ${DB_HOST:localhost}
  login: ${DB_LOGIN}
  password: ${DB_PASSWORD}
  driver: ${DB_DRIVER:postgres}
  showSql: ${DB_SHOW_SQL:false}
  maxIdleConns: ${DB_MAX_IDLE_CONNS:10}
  maxOpenConns: ${DB_MAX_OPEN_CONNS:100}
  connMaxLifetime: ${DB_CONN_MAX_LIFETIME:3600}
server:
  host: ${SERVER_HOST:*}
  port: ${SERVER_PORT:8080}
  maxSize: ${MAX_REQUEST_BODY_SIZE:104857600}
service:
  name: ${SERVICE_NAME}
log:
  level: ${LOGGING_ROOT_LEVEL:ERROR}
security:
  enable: ${ENABLE_SECURITY:true}
kafka:
  url: ${KAFKA_URL:localhost:9092}
  minBytes: ${KAFKA_MIN_BYTES:100}
  maxBytes: ${KAFKA_MAX_BYTES:10000}
  interval: ${KAFKA_COMMIT_INTERVAL:1}
